import streamlit as st
from agents import ask_the_government
import datetime

# 1. PAGE CONFIG
st.set_page_config(
    page_title="DK-OS Beta",
    page_icon="🇩🇰",
    layout="centered"
)

# 2. STYLES
st.markdown("""
<style>
    .stChatMessage {
        border-radius: 15px;
        padding: 10px;
    }
    .ministry-header {
        background-color: #f8f9fa;
        padding: 15px;
        border-radius: 10px;
        margin-bottom: 20px;
        text-align: center;
        border: 1px solid #e9ecef;
    }
    .beta-tag {
        color: #e67e22;
        font-weight: bold;
        font-size: 12px;
        border: 1px solid #e67e22;
        padding: 2px 6px;
        border-radius: 4px;
    }
</style>
""", unsafe_allow_html=True)

# 3. SIDEBAR
with st.sidebar:
    st.title("🇩🇰 DK-OS")
    st.markdown("<span class='beta-tag'>PUBLIC BETA v5.0</span>", unsafe_allow_html=True)
    st.caption("AI Government Assistant")
    
    st.markdown("---")
    st.success("🟢 Systems Online")
    
    st.info("""
    **Test Mode Active:**
    This system is currently in public testing.
    Answers are generated by AI and should be verified.
    """)
    
    st.markdown("---")
    if st.button("🗑️ Reset Chat", type="primary"):
        st.session_state.messages = []
        st.rerun()

# 4. HEADER
st.title("🇩🇰 DK-OS")
st.markdown("### Digital State Assistant")
st.markdown("*Ask questions or request document drafts (e.g., 'Write a complaint to my landlord').*")

# 5. CHAT LOGIC
if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"], unsafe_allow_html=True)

if prompt := st.chat_input("Type here... (Dansk, English, Türkçe)"):
    # 1. Mesajı Göster
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # 2. İŞLEM & İSTİHBARAT (LOGGING)
    with st.spinner("Processing request..."):
        # Loglama: Soruyu konsola yazdır (Sen bunu Streamlit panelinden göreceksin)
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{timestamp}] NEW QUERY: {prompt}") 
        
        response_data = ask_the_government(prompt)
        
        print(f"[{timestamp}] ASSIGNED TO: {response_data['category']}") # Hangi bakanlık cevapladı?

        # 3. Cevabı Formatla
        header_html = f"""
        <div class="ministry-header">
            <div style="font-size: 40px;">{response_data['ministry_icon']}</div>
            <div style="{response_data['ministry_style']} font-weight:bold; font-size: 18px;">{response_data['ministry_name']}</div>
        </div>
        """
        full_response = header_html + response_data["answer"]

    # 4. Cevabı Göster
    with st.chat_message("assistant"):
        st.markdown(full_response, unsafe_allow_html=True)
    
    st.session_state.messages.append({"role": "assistant", "content": full_response})